layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Swift
    web_url: https://developer.apple.com/swift/
    image_url: https://developer.apple.com/swift/images/swift-og.png

  #- name: Web design

  #- name: Sass
  #  web_url: https://github.com/topics/sass
  #  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
